[[headers]]
for = "/sensitive-directory/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Cache-Control = "no-store"

[[redirects]]
from = "/sensitive-directory/*"
to = "/404.html"
status = 404

[build]
publish = "player/"
